version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/development/php/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=calligrafm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - calligrafm-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 8000:80
    volumes:
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - php

volumes:
  calligrafm-db-data:
